// Browser-specific copy. Shared app strings are generated from the ten ARB catalogs.
const keys = [
  "browserIntro",
  "localOnly",
  "restrictedPage",
  "captureFailed",
  "emptyPage",
  "pageTooLarge",
  "privatePage",
  "storageFailed",
  "otherReader",
  "openPage",
  "openPageHint",
  "remove",
  "deleteConfirm",
  "shortcuts",
  "shortcutHint",
  "imagePrivacy",
  "sourcePage",
  "browserPrivacy",
  "getStarted",
  "readerHint",
];
const rows = {
  en: [
    "A little space for the words that matter.",
    "Saved only in this browser.",
    "This page cannot be read here. Open a normal webpage, then click Phralio.",
    "Could not capture this page. Check site access or paste the text instead.",
    "No readable article was found. Try pasting its text.",
    "This page is too large. Paste a shorter passage.",
    "Private pages are not saved. Paste text in a regular window if you want to keep it.",
    "Could not save locally. Free browser storage or remove an old reading, then retry.",
    "This reading was opened in another tab. Reopen it here to continue.",
    "Open webpage",
    "Open a public HTTPS page, then click Phralio in the browser toolbar to read it.",
    "Remove",
    "Remove this reading and its bookmarks from this browser?",
    "Keyboard shortcuts",
    "Space: play / pause · ← / →: one word · Shift + ← / →: sentence · Escape: pause / Home",
    "Only images already loaded by the page and accessible to the browser are copied. Others show their description.",
    "Source page",
    "No account, tracking or cloud sync. Readings, bookmarks and settings stay in this browser profile. Removing the extension removes its data.",
    "Click Phralio on any article to begin.",
    "Click to read · Scroll the passage to move word by word",
  ],
  ru: [
    "Немного места для важных слов.",
    "Сохранено только в этом браузере.",
    "Эту страницу прочитать нельзя. Откройте обычную веб-страницу и нажмите Phralio.",
    "Не удалось получить текст. Проверьте доступ к сайту или вставьте текст.",
    "Текст статьи не найден. Попробуйте вставить его.",
    "Страница слишком большая. Вставьте короткий отрывок.",
    "Приватные страницы не сохраняются. Чтобы сохранить текст, вставьте его в обычном окне.",
    "Не удалось сохранить. Освободите место или удалите старый текст и повторите.",
    "Текст открыт в другой вкладке. Откройте его здесь снова.",
    "Открыть веб-страницу",
    "Откройте публичную HTTPS-страницу и нажмите Phralio на панели браузера.",
    "Удалить",
    "Удалить этот текст и его закладки из браузера?",
    "Горячие клавиши",
    "Пробел: пуск / пауза · ← / →: слово · Shift + ← / →: предложение · Escape: пауза / Главная",
    "Копируются только уже загруженные и доступные браузеру изображения. Для остальных показано описание.",
    "Источник",
    "Без аккаунта, отслеживания и облачной синхронизации. Данные хранятся в этом профиле браузера. Удаление расширения удалит его данные.",
    "Нажмите Phralio на странице статьи.",
    "Нажмите для чтения · Прокручивайте текст по словам",
  ],
  es: [
    "Un espacio para las palabras que importan.",
    "Guardado solo en este navegador.",
    "Esta página no se puede leer aquí. Abre una página web normal y pulsa Phralio.",
    "No se pudo capturar la página. Revisa el acceso al sitio o pega el texto.",
    "No se encontró un artículo. Prueba a pegar el texto.",
    "La página es demasiado grande. Pega un fragmento más corto.",
    "Las páginas privadas no se guardan. Pega el texto en una ventana normal para conservarlo.",
    "No se pudo guardar. Libera espacio o elimina una lectura y reinténtalo.",
    "Esta lectura está abierta en otra pestaña. Vuelve a abrirla aquí.",
    "Abrir página web",
    "Abre una página HTTPS pública y pulsa Phralio en la barra del navegador.",
    "Eliminar",
    "¿Eliminar esta lectura y sus marcadores de este navegador?",
    "Atajos de teclado",
    "Espacio: leer / pausa · ← / →: palabra · Mayús + ← / →: frase · Escape: pausa / Inicio",
    "Solo se copian imágenes ya cargadas y accesibles. Las demás muestran su descripción.",
    "Página de origen",
    "Sin cuenta, seguimiento ni sincronización. Los datos quedan en este perfil del navegador. Desinstalar la extensión elimina sus datos.",
    "Pulsa Phralio en cualquier artículo para empezar.",
    "Pulsa para leer · Desplaza el texto palabra por palabra",
  ],
  pt: [
    "Espaço para as palavras que importam.",
    "Guardado apenas neste navegador.",
    "Esta página não pode ser lida aqui. Abre uma página normal e clica em Phralio.",
    "Não foi possível obter a página. Verifica o acesso ao site ou cola o texto.",
    "Nenhum artigo encontrado. Experimenta colar o texto.",
    "Página demasiado grande. Cola um excerto mais curto.",
    "Páginas privadas não são guardadas. Cola o texto numa janela normal para o guardar.",
    "Não foi possível guardar. Liberta espaço ou remove uma leitura e tenta novamente.",
    "Esta leitura está aberta noutro separador. Abre-a novamente aqui.",
    "Abrir página web",
    "Abre uma página HTTPS pública e clica em Phralio na barra do navegador.",
    "Remover",
    "Remover esta leitura e os seus marcadores deste navegador?",
    "Atalhos de teclado",
    "Espaço: ler / pausa · ← / →: palavra · Shift + ← / →: frase · Escape: pausa / Início",
    "Só são copiadas imagens já carregadas e acessíveis. As restantes mostram a descrição.",
    "Página de origem",
    "Sem conta, rastreamento ou sincronização. Os dados ficam neste perfil. Desinstalar a extensão elimina os dados.",
    "Clica em Phralio num artigo para começar.",
    "Clica para ler · Desloca o texto palavra por palavra",
  ],
  zh: [
    "为重要的文字留一点空间。",
    "仅保存在此浏览器中。",
    "无法阅读此页面。请打开普通网页，然后点击 Phralio。",
    "无法提取页面。请检查网站访问权限或粘贴文字。",
    "未找到可读文章。请尝试粘贴文字。",
    "页面过大。请粘贴较短的段落。",
    "不会保存隐私页面。如需保存，请在普通窗口中粘贴文字。",
    "无法保存。请释放存储空间或删除旧阅读内容后重试。",
    "此内容已在另一个标签页中打开。请在此处重新打开。",
    "打开网页",
    "打开公共 HTTPS 页面，然后点击浏览器工具栏中的 Phralio。",
    "删除",
    "从此浏览器中删除此阅读内容及其书签？",
    "键盘快捷键",
    "空格：播放/暂停 · ←/→：单词 · Shift + ←/→：句子 · Escape：暂停/主页",
    "只复制网页已加载且浏览器可访问的图片。其他图片显示文字说明。",
    "原始页面",
    "无需账户，不跟踪，不进行云同步。数据仅保存在此浏览器配置文件中。卸载扩展会删除其数据。",
    "在文章页面点击 Phralio 即可开始。",
    "点击阅读 · 滚动文本可逐词移动",
  ],
  ja: [
    "大切な言葉のための、小さな余白。",
    "このブラウザにのみ保存します。",
    "このページは読めません。通常のウェブページを開き、Phralio をクリックしてください。",
    "ページを取得できません。サイトへのアクセスを確認するか、文章を貼り付けてください。",
    "記事が見つかりません。文章を貼り付けてみてください。",
    "ページが大きすぎます。短い文章を貼り付けてください。",
    "プライベートページは保存しません。保存するには通常のウインドウで文章を貼り付けてください。",
    "保存できません。空き容量を増やすか、古い文章を削除して再試行してください。",
    "別のタブで開かれています。ここでもう一度開いてください。",
    "ウェブページを開く",
    "公開 HTTPS ページを開き、ブラウザのツールバーで Phralio をクリックしてください。",
    "削除",
    "この文章とブックマークをブラウザから削除しますか？",
    "キーボードショートカット",
    "スペース：再生/一時停止 · ←/→：単語 · Shift + ←/→：文 · Escape：一時停止/ホーム",
    "読み込み済みでアクセス可能な画像のみコピーします。他は説明を表示します。",
    "元のページ",
    "アカウント、追跡、クラウド同期はありません。データはこのブラウザのプロファイルに保存されます。拡張機能を削除するとデータも削除されます。",
    "記事で Phralio をクリックして始めましょう。",
    "クリックして読む · 文章をスクロールして単語ごとに移動",
  ],
  pl: [
    "Trochę miejsca na ważne słowa.",
    "Zapisane tylko w tej przeglądarce.",
    "Nie można odczytać tej strony. Otwórz zwykłą stronę i kliknij Phralio.",
    "Nie udało się pobrać treści. Sprawdź dostęp do strony lub wklej tekst.",
    "Nie znaleziono artykułu. Spróbuj wkleić tekst.",
    "Strona jest za duża. Wklej krótszy fragment.",
    "Strony prywatne nie są zapisywane. Wklej tekst w zwykłym oknie, aby go zachować.",
    "Nie udało się zapisać. Zwolnij miejsce lub usuń starą lekturę i spróbuj ponownie.",
    "Ta lektura jest otwarta w innej karcie. Otwórz ją ponownie tutaj.",
    "Otwórz stronę",
    "Otwórz publiczną stronę HTTPS i kliknij Phralio na pasku przeglądarki.",
    "Usuń",
    "Usunąć tę lekturę i jej zakładki z przeglądarki?",
    "Skróty klawiaturowe",
    "Spacja: czytaj / pauza · ← / →: słowo · Shift + ← / →: zdanie · Escape: pauza / Główna",
    "Kopiowane są tylko załadowane i dostępne obrazy. Pozostałe pokazują opis.",
    "Strona źródłowa",
    "Bez konta, śledzenia i synchronizacji. Dane pozostają w tym profilu przeglądarki. Usunięcie rozszerzenia usuwa dane.",
    "Kliknij Phralio na stronie artykułu, aby zacząć.",
    "Kliknij, aby czytać · Przewijaj tekst słowo po słowie",
  ],
  de: [
    "Raum für die Worte, die zählen.",
    "Nur in diesem Browser gespeichert.",
    "Diese Seite kann hier nicht gelesen werden. Öffne eine normale Webseite und klicke auf Phralio.",
    "Die Seite konnte nicht erfasst werden. Prüfe den Websitezugriff oder füge den Text ein.",
    "Kein lesbarer Artikel gefunden. Füge den Text ein.",
    "Diese Seite ist zu groß. Füge einen kürzeren Abschnitt ein.",
    "Private Seiten werden nicht gespeichert. Füge Text in einem normalen Fenster ein, um ihn zu behalten.",
    "Speichern fehlgeschlagen. Gib Speicher frei oder entferne einen alten Text und versuche es erneut.",
    "Dieser Text wurde in einem anderen Tab geöffnet. Öffne ihn hier erneut.",
    "Webseite öffnen",
    "Öffne eine öffentliche HTTPS-Seite und klicke in der Browserleiste auf Phralio.",
    "Entfernen",
    "Diesen Text und seine Lesezeichen aus diesem Browser entfernen?",
    "Tastenkürzel",
    "Leertaste: Lesen / Pause · ← / →: Wort · Umschalt + ← / →: Satz · Escape: Pause / Start",
    "Nur bereits geladene, zugängliche Bilder werden kopiert. Andere zeigen ihre Beschreibung.",
    "Quellseite",
    "Kein Konto, Tracking oder Cloud-Abgleich. Daten bleiben in diesem Browserprofil. Beim Entfernen der Erweiterung werden ihre Daten gelöscht.",
    "Klicke bei einem Artikel auf Phralio, um zu beginnen.",
    "Klicken zum Lesen · Text Wort für Wort scrollen",
  ],
  fr: [
    "Un peu de place pour les mots qui comptent.",
    "Enregistré uniquement dans ce navigateur.",
    "Cette page ne peut pas être lue ici. Ouvrez une page web ordinaire et cliquez sur Phralio.",
    "Impossible de récupérer la page. Vérifiez les autorisations ou collez le texte.",
    "Aucun article lisible trouvé. Essayez de coller le texte.",
    "Cette page est trop grande. Collez un passage plus court.",
    "Les pages privées ne sont pas enregistrées. Collez le texte dans une fenêtre normale pour le conserver.",
    "Échec de la sauvegarde. Libérez du stockage ou supprimez une ancienne lecture, puis réessayez.",
    "Cette lecture est ouverte dans un autre onglet. Rouvrez-la ici.",
    "Ouvrir une page web",
    "Ouvrez une page HTTPS publique, puis cliquez sur Phralio dans la barre du navigateur.",
    "Supprimer",
    "Supprimer cette lecture et ses signets de ce navigateur ?",
    "Raccourcis clavier",
    "Espace : lire / pause · ← / → : mot · Maj + ← / → : phrase · Échap : pause / Accueil",
    "Seules les images déjà chargées et accessibles sont copiées. Les autres affichent leur description.",
    "Page source",
    "Sans compte, suivi ni synchronisation. Les données restent dans ce profil. Désinstaller l’extension supprime ses données.",
    "Cliquez sur Phralio dans un article pour commencer.",
    "Cliquez pour lire · Faites défiler le texte mot par mot",
  ],
  it: [
    "Spazio per le parole che contano.",
    "Salvato solo in questo browser.",
    "Questa pagina non è leggibile qui. Apri una pagina web normale e fai clic su Phralio.",
    "Impossibile acquisire la pagina. Controlla l’accesso al sito o incolla il testo.",
    "Nessun articolo leggibile trovato. Prova a incollare il testo.",
    "La pagina è troppo grande. Incolla un brano più breve.",
    "Le pagine private non vengono salvate. Incolla il testo in una finestra normale per conservarlo.",
    "Salvataggio non riuscito. Libera spazio o rimuovi una lettura e riprova.",
    "Questa lettura è aperta in un’altra scheda. Riaprila qui.",
    "Apri pagina web",
    "Apri una pagina HTTPS pubblica, poi fai clic su Phralio nella barra del browser.",
    "Rimuovi",
    "Rimuovere questa lettura e i suoi segnalibri da questo browser?",
    "Scorciatoie da tastiera",
    "Spazio: leggi / pausa · ← / →: parola · Maiusc + ← / →: frase · Esc: pausa / Home",
    "Vengono copiate solo le immagini già caricate e accessibili. Per le altre viene mostrata la descrizione.",
    "Pagina di origine",
    "Nessun account, tracciamento o sincronizzazione. I dati restano in questo profilo. Disinstallando l’estensione si eliminano i suoi dati.",
    "Fai clic su Phralio su un articolo per iniziare.",
    "Fai clic per leggere · Scorri il testo parola per parola",
  ],
};
export const extensionCopy = Object.fromEntries(
  Object.entries(rows).map(([locale, values]) => [
    locale,
    Object.fromEntries(keys.map((key, i) => [key, values[i]])),
  ]),
);
